export const symptomsList: string[] = [
  "Fever",
  "Headache",
  "Cough",
  "Sore Throat",
  "Runny Nose",
  "Fatigue",
  "Bloating",
  "Nausea",
  "Vomiting",
  "Diarrhea",
  "Shortness of Breath",
  "Chest Pain",
  "Loss of Taste or Smell",
  "Muscle Aches",
  "Joint Pain",
  "Itching",
  "Sneezing",
  "Skin Rash",
  "Other",
];
